platform :ios, '9.0'

target 'diap' do
  use_frameworks!

  pod 'Moya'
  pod 'SnapKit'
  pod 'SwiftMessages'
  pod 'NVActivityIndicatorView'
  pod 'Alamofire'

 target 'diapTests' do
        inherit! :search_paths
        pod 'Alamofire'
    end
end



